defaults:
  - scope:
      path: ''
    values:
      layout: default

exclude:
  - CHANGELOG.md
  - docker-compose.yaml
  - LICENSE
  - makefile
  - package.json
  - package-lock.json
  - postcss.config.js
  - README.md
  - tailwind.config.js

title: JHAE GitHub Page Theme

# -> GitHub metadata plugin
repository: jhae-de/github-page-theme
# <- GitHub metadata plugin
