assets:
  logo: /assets/images/logo.svg

paths:
  fonts: /assets/fonts
  images: /assets/images

theme:
  colors:
    brand: '#202830'
    favicon:
      android-theme: '#202830'
      windows-tile: '#ffffff'
